export interface Student {
  id?: number,
  cne: string,
  first_name?: string,
  last_name?: string,
  phone: string,
  email: string,
  genre?: string,
  image_url?: string,
  date_of_birth?: string,
  password: string,
  gender?:string,
  firstname?:string,
  lastname?:string,
}
